apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-demo
resources:
- namespace.yml
- https://github.com/open-telemetry/opentelemetry-demo/kubernetes/opentelemetry-demo.yaml
