apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-servicemonitor
  labels:
    environment: dev
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    targetPort: 9090
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
